package com.example.healthloop.presentation.add_entry

import androidx.lifecycle.viewModelScope
import com.example.healthloop.domain.usecase.AddHealthEntryUseCase
import com.example.healthloop.presentation.mapper.toDomain
import com.example.healthloop.presentation.model.HealthEntryUiModel
import com.example.healthloop.presentation.model.UiState
import com.example.healthloop.presentation.viewmodel.BaseViewModel
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.*
import javax.inject.Inject

@HiltViewModel
class AddEntryViewModel @Inject constructor(
    private val addHealthEntryUseCase: AddHealthEntryUseCase
) : BaseViewModel<AddEntryUiState>() {

    private val _waterIntake = MutableStateFlow("")
    val waterIntake: StateFlow<String> = _waterIntake.asStateFlow()

    private val _sleepHours = MutableStateFlow("")
    val sleepHours: StateFlow<String> = _sleepHours.asStateFlow()

    private val _stepCount = MutableStateFlow("")
    val stepCount: StateFlow<String> = _stepCount.asStateFlow()

    private val _selectedMood = MutableStateFlow("")
    val selectedMood: StateFlow<String> = _selectedMood.asStateFlow()

    private val _weight = MutableStateFlow("")
    val weight: StateFlow<String> = _weight.asStateFlow()

    private val _saveSuccess = MutableStateFlow(false)
    val saveSuccess: StateFlow<Boolean> = _saveSuccess.asStateFlow()

    init {
        updateState(UiState.Success(AddEntryUiState()))
    }

    fun updateWaterIntake(value: String) {
        if (value.isEmpty() || value.toIntOrNull() != null) {
            _waterIntake.value = value
        }
    }

    fun updateSleepHours(value: String) {
        if (value.isEmpty() || value.toFloatOrNull() != null) {
            _sleepHours.value = value
        }
    }

    fun updateStepCount(value: String) {
        if (value.isEmpty() || value.toIntOrNull() != null) {
            _stepCount.value = value
        }
    }

    fun updateMood(value: String) {
        _selectedMood.value = value
    }

    fun updateWeight(value: String) {
        if (value.isEmpty() || value.toFloatOrNull() != null) {
            _weight.value = value
        }
    }

    fun saveEntry() {
        viewModelScope.launch {
            try {
                updateState(UiState.Loading)

                // Validate inputs
                val waterIntakeValue = _waterIntake.value.toIntOrNull() ?: 0
                val sleepHoursValue = _sleepHours.value.toFloatOrNull() ?: 0f
                val stepCountValue = _stepCount.value.toIntOrNull() ?: 0
                val weightValue = _weight.value.toFloatOrNull() ?: 0f

                if (_selectedMood.value.isEmpty()) {
                    updateState(UiState.Error("Please select your mood"))
                    return@launch
                }

                // Create health entry with formatted date string
                val healthEntry = HealthEntryUiModel(
                    id = 0, // Will be auto-generated by database
                    date = Date(), // Use current Date object
                    waterIntake = waterIntakeValue,
                    sleepHours = sleepHoursValue,
                    stepCount = stepCountValue,
                    mood = _selectedMood.value,
                    weight = weightValue
                )

                // Save to database using use case
                addHealthEntryUseCase(healthEntry.toDomain())

                // Set success flag
                _saveSuccess.value = true

                // Reset form
                resetForm()

                updateState(UiState.Success(AddEntryUiState(isSaved = true)))
            } catch (e: Exception) {
                updateState(UiState.Error(e.message ?: "Failed to save entry"))
            }
        }
    }

    private fun resetForm() {
        _waterIntake.value = ""
        _sleepHours.value = ""
        _stepCount.value = ""
        _selectedMood.value = ""
        _weight.value = ""
    }

    /**
     * Format current date as string for UI display
     */
    private fun formatCurrentDate(): String {
        return try {
            val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
            dateFormat.format(Date())
        } catch (e: Exception) {
            "Today"
        }
    }

    /**
     * Clear the save success flag
     */
    fun clearSaveSuccess() {
        _saveSuccess.value = false
    }

    /**
     * Get current timestamp for domain layer
     */
    fun getCurrentTimestamp(): Long {
        return Date().time
    }
}

data class AddEntryUiState(val isSaved: Boolean = false)